# Generated by Django 2.2.4 on 2020-02-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addentance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='division',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
