# Generated by Django 2.2.4 on 2020-02-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addentance', '0002_class_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_abr',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(max_length=100),
        ),
    ]
