# Generated by Django 2.2.4 on 2020-02-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addentance', '0003_auto_20200215_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_abr',
            field=models.CharField(max_length=7),
        ),
    ]
