# Generated by Django 3.0.3 on 2020-02-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addentance', '0005_auto_20200216_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
