# Generated by Django 3.0.3 on 2020-02-16 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addentance', '0006_remove_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendance_s',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addentance.Student'),
        ),
    ]
