# Generated by Django 3.0.3 on 2020-02-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addentance', '0007_auto_20200216_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='addentance.Subject'),
        ),
    ]
