# Generated by Django 3.0.3 on 2020-02-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addentance', '0008_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addentance.Class'),
        ),
    ]
