# Generated by Django 3.0.3 on 2020-02-18 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addentance', '0011_auto_20200218_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='class_s',
        ),
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ManyToManyField(to='addentance.Attendance')),
                ('class_s', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addentance.Class')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addentance.Student')),
            ],
        ),
    ]
