# Generated by Django 2.2.4 on 2020-02-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addentance', '0013_auto_20200227_2054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher_Details',
            new_name='Teacher_Detail',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
    ]
