# Generated by Django 3.0.3 on 2020-02-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addentance', '0014_auto_20200227_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attended',
            new_name='not_attended',
        ),
    ]
