# Generated by Django 2.2.4 on 2020-03-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addentance', '0017_auto_20200303_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='detailed_attendance',
            field=models.ManyToManyField(to='addentance.AttendanceTimestamp'),
        ),
    ]
