# Generated by Django 2.2.4 on 2020-03-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addentance', '0018_attendance_detailed_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetimestamp',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
