# Generated by Django 2.2.4 on 2020-03-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addentance', '0019_auto_20200305_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetimestamp',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
