# Generated by Django 2.2.4 on 2020-03-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addentance', '0020_auto_20200306_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetimestamp',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
