# Generated by Django 2.2.4 on 2020-03-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addentance', '0023_auto_20200307_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetimestamp',
            name='present',
            field=models.BooleanField(default=True),
        ),
    ]
